#==================#
#    wallpapers    #
#==================#


# bind = $mainMod, W, exec, lightDark.sh redhat
bind = $mainMod, W, exec, uwsm app -t service bash light-or-dark.sh athena
bind = $mainMod, R, exec, uwsm app -t service bash light-or-dark.sh dark
bind = $mainMod, E, exec, uwsm app -t service bash light-or-dark.sh light
