# opacity for certain class/ title
# windowrule = tag +Opaque, match:class (imv)
windowrule = tag +Opaque, match:class vlc
windowrule = tag +Opaque, match:class mpv
windowrule = tag +Opaque, match:class org.gnome.Evince
windowrule = tag +Opaque, match:class thunderbird
windowrule = tag +Opaque, match:class virt-manager
windowrule = tag +Opaque, match:class firefox
windowrule = tag +Opaque, match:class chromium
windowrule = tag +Opaque, match:class Firefox Beta
windowrule = tag +Opaque, match:class firefoxnightly
windowrule = tag +Opaque, match:class io.freetubeapp.FreeTube
windowrule = tag +Opaque, match:class imv
windowrule = tag +Opaque, match:class org.gnome.Loupe
windowrule = tag +Opaque, match:class org.inkscape.Inkscape
windowrule = tag +Opaque, match:title qiv:(.*)

# Opacity Title based
windowrule = tag +Opaque, match:title (.*)(Prime Video)(.*)
windowrule = tag +Opaque, match:title (.*)Netflix(.*)
windowrule = tag +Opaque, match:title (.*)(- Google Docs - Chromium)
# windowrule = opaque, match:title (Prime Video)(.*)
windowrule = tag +Opaque, match:title (.*)Prime Video(.*)
windowrule = tag +Opaque, match:title (.*)YouTube(.*)
windowrule = tag +Opaque, match:title (Instagram)(.*)
windowrule = tag +Opaque, match:class (.*)(libreoffice)(.*)
windowrule = tag +Opaque, match:class  org.inkscape.Inkscape
# windowrule = tag +Opaque, match:title  yazi:(.*)
# windowrule = tag +Opaque, match:title  f
windowrule = tag +Opaque, match:title (.*) – Hyprland Wiki — (.*)
# windowrule = opaque, match:title (.*)ArchWiki — (.*)
windowrule = tag +Opaque, match:title (.*)DuckDuckGo(.*)
windowrule = tag +Opaque, match:title (.*) Brave Search — Mozilla Firefox
windowrule = tag +Opaque, match:title (.*)Arch(.*)
windowrule = tag +Opaque, match:title GitHub(.*)


