#===========================#
# Flating Window Rule       #
#===========================#

# Set floating size for kitty when it is float

windowrulev2 = maxsize 750 650, class:^(kitty)$,floating: 1
windowrulev2 = tag +FSize, class:foot
windowrulev2 = maxsize 750 650, class:foot,floating: 1
windowrulev2 = center, class:^(kitty)$, floating: 1

# XDG desktop portal popup
windowrulev2 = tag +Float, title:(), tag:WebBrowser
windowrulev2 = tag +Float, title:(Library), tag:WebBrowser
windowrulev2 = size 660 500, title:(Library), tag:WebBrowser
# windowrulev2 = size 787 600, title:(), tag:WebBrowser
windowrulev2 = tag +Float, tag:FILE_OP
windowrulev2 = size 787 600, tag:FILE_OP
windowrulev2 = size 587 400, title:(Opening)(.*)$, tag:WebBrowser
windowrulev2 = move 462 231, tag:FILE_OP

#============================#
# Floating Window Auto       #
#============================#
# hyprland share picker
windowrulev2 = tag +Float, class:(hyprland-share-picker)
windowrulev2 = size 650 450, class:(hyprland-share-picker)
windowrulev2 = move 601 183, class:(hyprland-share-picker)

# nm-applet
windowrulev2 = tag +Float, tag:NetWork
windowrulev2 = pin, class: tag:NetWork
windowrulev2 = move 601 183, tag:NetWork
windowrulev2 = size 750 650, class:(nm-connection-editor)
windowrulev2 = opaque, class:(nm-connection-editor)

# KeePassXC
windowrulev2 = tag +Float, title:(passdef - KeePassXC)
windowrulev2 = size 800 650, title:(passdef - KeePassXC)
windowrulev2 = move 601 183, title:(passdef - KeePassXC)
windowrulev2 = opaque, class:(org.keepassxc.KeePassXC)

windowrulev2 = tag +Float, class: (org.keepassxc.KeePassXC)
windowrulev2 = pin, class: (org.keepassxc.KeePassXC)
windowrulev2 = size 800 650, class: (org.keepassxc.KeePassXC),title: (Passwords.kdbx)(.*)$
windowrulev2 = move 601 183, class: (org.keepassxc.KeePassXC),title: (Passwords.kdbx)(.*)$

# Audio Controller (easy easyeffects, pwvucontrol, overskyride)
windowrulev2 = tag +Float, tag:Audio_ctl
windowrulev2 = pin, tag:Audio_ctl
windowrulev2 = size 750 550, tag:Audio_ctl
windowrulev2 = move 601 183, tag:Audio_ctl

# Show Me the Key
windowrulev2 = float, class:(showmethekey-gtk)
windowrulev2 = size 669 68, class:(showmethekey-gtk)
windowrulev2 = move 42 1067, class:(showmethekey-gtk)
windowrulev2 = pin, class:(showmethekey-gtk)
windowrulev2 = opaque, class:(showmethekey-gtk)

windowrulev2 = float, class:(org.twosheds.iwgtk)
windowrulev2 = move 1442 57, class:(org.twosheds.iwgtk)
# night_mode_popup
windowrulev2 = float, class:(night_mode)
# windowrulev2 = bordercolor rgb(5A6446), class:(night_mode)
windowrulev2 = move 860 320, class:(night_mode)

# firewall applet
windowrulev2 = float, title:(firewall-applet)
# windowrulev2 = move 1600 57, title:(firewall-applet)
windowrulev2 = float, title:(About Firewall Applet)

# Gnome Calculator
windowrulev2 = float, class:(org.gnome.Calculator)
windowrulev2 = size 360 616, class:(org.gnome.Calculator)

# idleinhibit

windowrulev2 = idleinhibit focus, title:^(YouTube)$

# Gimp
windowrulev2 = opaque, initialTitle:(GNU Image Manipulation Program)

# Hyprland dialog
windowrulev2 = move 491 92, class: hyprland-dialog

# Yubikey
windowrulev2 = tag +Float, tag:Yubico
windowrulev2 = size 750 700, tag:Yubico
windowrulev2 = pin, tag:Yubico

# ANIMATION
windowrulev2 = animation slide, class:(org.keepassxc.KeePassXC)
windowrulev2 = animation slide, class: hyprland-dialog

# ueberzugpp
# windowrulev2 = animation popin 80%, class:ueberzugpp(.*)
windowrulev2 = noanim, class:ueberzugpp(.*)

