# Tags - Terminal Emulator
windowrule = tag +term, match:class Alacritty
windowrule = tag +term, match:class kitty
windowrule = tag +term, match:class foot
windowrule = tag +term, match:class footclient

# Tags - Browser
windowrule = tag +WebBrowser, match:class (firefox)
windowrule = tag +WebBrowser, match:class (Firefox Beta)
windowrule = tag +WebBrowser, match:class (chromium)

#File Opener, Downloads Uploads etc
windowrule = tag +FILE_OP, match:title (Open Files)
windowrule = tag +FILE_OP, match:title (Open File)
windowrule = tag +FILE_OP, match:title (Open File)(.*)
windowrule = tag +FILE_OP, match:title (Select File)(.*)$
windowrule = tag +FILE_OP, match:title (Open Document)
windowrule = tag +FILE_OP, match:title (Save As)(.*)$
windowrule = tag +FILE_OP, match:title (All Files)
windowrule = tag +FILE_OP, match:title (File Upload)
windowrule = tag +FILE_OP, match:title (File Upload)(.*)$
windowrule = tag +FILE_OP, match:initial_title (Save Image)
windowrule = tag +FILE_OP, match:initial_title (Save Image)(.*)$
windowrule = tag +FILE_OP, match:initial_title (Task Manager - Chromium)

#windowrule = tag +noGroup, match:class chromium
# windowrule = tag +noGroup, match:class firefox
windowrule = tag +noGroup, match:class (hyprland-share-picker)
windowrule = tag +noGroup, match:tag (Audio_ctl)
# windowrule = tag +noGroup, match:class firefoxnightly
# windowrule = tag +noGroup, match:class imv

# Email cliant
windowrule = tag +email, match:class (org.mozilla.Thunderbird)
windowrule = tag +email, match:class (eu.betterbird.Betterbird)

# finance
windowrule = tag +finance, match:class gnucash
windowrule = tag +noGroup, match:class gnucash
windowrule = tag +Opaque, match:class gnucash

# Audio control softwares (easy effects etc)
windowrule = tag +Audio_ctl, match:class (com.saivert.pwvucontrol)
windowrule = tag +Audio_ctl, match:class (com.github.wwmm.easyeffects)
windowrule = tag +Audio_ctl, match:class (io.github.kaii_lb.Overskride)

# NetworkManager
windowrule = tag +NetWork, match:class (nm-connection-editor)
windowrule = tag +NetWork, match:class (nm-applet)

# Yubico
windowrule = tag +Yubico, match:class (com.yubico.yubioath)
windowrule = tag +Yubico, match:class (authenticator)

# SwayNC
layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window

