# Tags - Class based
windowrulev2 = tag +term, class:Alacritty
windowrulev2 = tag +term, class:kitty
windowrulev2 = tag +term, class:foot

# Tags - Browser
windowrulev2 = tag +WebBrowser, class:(firefox)
windowrulev2 = tag +WebBrowser, class:(Firefox Beta)
windowrulev2 = tag +WebBrowser, class:(chromium)

#File Opener

windowrulev2 = tag +FILE_OP, title:(Open Files)
windowrulev2 = tag +FILE_OP, title:(Open File)

#windowrulev2 = tag +noGroup, class:chromium
windowrulev2 = tag +noGroup, class:firefox
windowrulev2 = tag +noGroup, class:(hyprland-share-picker)

# windowrulev2 = tag +noGroup, class:firefoxnightly

# windowrulev2 = tag +noGroup, class:imv

windowrulev2 = tag +email, class:(org.mozilla.Thunderbird)
windowrulev2 = tag +email, class:(eu.betterbird.Betterbird)

windowrulev2 = tag +finance, class:gnucash
windowrulev2 = tag +noGroup, class:gnucash
windowrulev2 = tag +Opaque, class:gnucash

layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window

